clear
addpath(genpath(cd))

% cingulateConnectivity — full analysis pipeline and figure generation.
%
% Run preflight.m on a new machine or when adding new subjects.
% Edit stim_filter.txt to control which stimulation conditions, amplitudes,
% and epoch windows are processed (auto-generated by buildStimConfig.m).
%
% Each stage loads its inputs from disk and saves outputs to data/, so
% individual stages can be re-run independently without repeating the full
% pipeline.

% -------------------------------------------------------------------------
% Stage 1 — Preprocessing
% -------------------------------------------------------------------------
% Iterates over all subjects and stimulation conditions matching
% stim_filter.txt. For each .dat file: loads raw BCI2000 signals, removes
% stimulation artifacts via bidirectional interpolation, cleans (highpass +
% 60Hz notch), re-references (small Laplacian and common average), epochs
% around stimulus onset, z-scores to pre-stimulus baseline, and extracts
% broadband Hilbert envelopes across 7 frequency bands. Outputs one
% preprocessed struct per file to data/preprocessed/ and Hilbert structs
% to data/hilbert/.
run("code/engine/dataPreprocess.m")

% -------------------------------------------------------------------------
% Stage 2 — Pairwise coherence
% -------------------------------------------------------------------------
% For each preprocessed file, computes pairwise Spearman rank correlations
% across all trial combinations for every recording channel, in separate
% task (0 to +570 ms post-stimulus) and baseline (0 to -850 ms) windows.
% Characterizes the response-vs-baseline shift per channel: Cohen's d,
% variance change, Wilcoxon ranksum p-value, and mean rho. Outputs one
% .mat per file to data/coherence/.
run("code/engine/extractCoherence.m")

% -------------------------------------------------------------------------
% Stage 3 — N1/N2 waveform peak extraction
% -------------------------------------------------------------------------
% Detects N1 (10–50 ms post-stimulus) and N2 (60–700 ms post-stimulus)
% peaks from the mean CCEP waveform (small Laplacian, z-scored) for each
% channel. Extracts peak amplitude and latency. Outputs one .mat per file
% to data/waveformFeatures/.
run("code/engine/extractResponseFeatures.m")

% -------------------------------------------------------------------------
% Stage 4 — Broadband gamma envelope features
% -------------------------------------------------------------------------
% Applies changepoint detection to the z-scored broadband gamma (70–170 Hz)
% Hilbert envelope to identify post-stimulus response onset, offset, and
% peak amplitude for each channel. Features are computed relative to a
% pre-stimulus baseline window, excluding the artifact and N1 periods.
% Outputs one .mat per file to data/gamma/.
run("code/engine/extractGamma.m")

% -------------------------------------------------------------------------
% Stage 5 — Broadband LF phase and magnitude features
% -------------------------------------------------------------------------
% Applies changepoint detection to the broadband LF (5–40 Hz) magnitude
% envelope to characterize the post-stimulus response window. Extracts the
% 3 most prominent phase angle extrema from the response period using
% characterizeAngleResponse. Outputs one .mat per file to data/phase/.
run("code/engine/extractPhase.m")

% -------------------------------------------------------------------------
% Stage 6 — Data pooling
% -------------------------------------------------------------------------
% Concatenates all per-file outputs from stages 2–5 across all subjects
% and conditions into a single pooledData struct. Annotates each
% observation with electrode coordinates, atlas region labels, and
% stimulated region identity. Computes channel-level RMS task-vs-baseline
% p-values. Outputs data/pooledData.mat.
run("code/engine/poolData.m")

% -------------------------------------------------------------------------
% Stage 7 — Feature matrix compilation for machine learning
% -------------------------------------------------------------------------
% Reshapes pooledData into a struct array and a numeric feature matrix
% ready for classifier input. Assigns 6-class labels based on stimulated
% hemisphere and cingulate subregion: right/left ACC (1/2), MCC (3/4),
% PCC (5/6). Outputs data/compiledData.mat and data/compiledDataMatrix.mat.
run("code/engine/compileData.m")

% -------------------------------------------------------------------------
% Stage 8 — Inter-channel coherence network (computationally intensive)
% -------------------------------------------------------------------------
% Computes cross-channel CCEP coherence across all brain region pairs using
% pairwise cross-correlations with lag. Identifies statistically significant
% inter-regional connectivity patterns beyond the primary stimulation-site
% analysis. Outputs data/interChannelCoherenceSignificant.mat. Not required
% for figures 2–3 and 5–7; required for figure 4 and clusterNetworkTool.
run("code/engine/extractInterChanCoherence.m")

% -------------------------------------------------------------------------
% Figure generation
% -------------------------------------------------------------------------
% Generates all manuscript figures (2–7) and supplemental figures (Supp 2,
% Supp 3). Figure 1 and suppFig1 require pooledBrain.mat and must be run
% manually. Closes all figure windows between scripts to prevent memory
% buildup. See runFigures.m for the individual figure script sequence.
run("code/engine/runFigures.m")
