clear
addpath(genpath(cd))

% Specify directories
dataDirectory = 'data/raw';
saveDirectory = 'data/preprocessed/';
saveHilbert   = 'data/hilbert/';
mkdir(saveDirectory);
mkdir(saveHilbert);
spesFolder = 'ElectricalStimulation_1HzStim/ECOG001/';

% Load preprocessing filter config.
% If stim_filter.txt does not exist, it is auto-generated by scanning all
% subject stimulation tables. Review the file and re-run to apply filters.
if ~isfile('stim_filter.txt')
    fprintf('stim_filter.txt not found -- running buildStimConfig()...\n\n');
    buildStimConfig(dataDirectory);
    fprintf('Review stim_filter.txt, comment out any conditions to exclude,\nthen re-run dataPreprocess.m.\n');
    return
end
cfg = readStimFilter('stim_filter.txt');

% Import dependencies
load("code/dependencies/SEEGClinical22ChanLoc_xyz.mat")  % EEG channel info
regionNames = cfg.regions;

% Identify subject folders
files    = dir(dataDirectory);
dirFlags = [files.isdir];
folders  = files(dirFlags);
subjects = {folders(3:end).name};

% Outer loop: iterate through all subjects
for subj = 1:length(subjects)

    currentSubject   = subjects{subj};
    subjectDirectory = [dataDirectory '/' currentSubject '/'];

    if ~isfile([subjectDirectory 'preprocessComplete.txt'])

        % Load stimulation table and channel inspection info
        load([subjectDirectory 'channelInspection.mat']);
        stimTable = readtable([subjectDirectory 'stimulationTable.xlsx']);

        % Load baseline data, VERA struct, and handle variability in
        % baseline data collection
        VERA = load([subjectDirectory currentSubject '_APARC2009_MNIbrain.mat']);
        [baseSig, baseStates, baseParams] = importBaseline(subjectDirectory);

        % Align VERA with data channels, annotate stimTable with anatomical
        % IDs, and filter files by configured stimulation conditions
        [VERA, stimTable, EEGChannels, filesOut, namesOut] = processChannels( ...
            VERA, channelInspection, stimTable, baseParams.ChannelNames.Value, ...
            regionNames, cfg.amplitudes, cfg.frequencies);
        writetable(stimTable, [subjectDirectory 'stimulationTable.xlsx'])

        for file = 1:length(filesOut)

            currentFile        = filesOut{file};
            tableIdx           = find(ismember(stimTable.file, currentFile));
            currentRegion      = {stimTable.ch1ID{tableIdx}, stimTable.ch2ID{tableIdx}};
            stimulatedChannels = [stimTable.ch1(tableIdx), stimTable.ch2(tableIdx)];

            if ~isfile([saveDirectory currentSubject '_' currentFile '_' namesOut{file} '.mat'])

                [data, hilbertSeeg, hilbertEeg] = preprocessData( ...
                    [subjectDirectory spesFolder currentFile '.dat'], ...
                    baseSig, EEGChannels, channelInspection, currentRegion, ...
                    VERA, currentSubject, ...
                    stimTable.currentAmplitude(tableIdx), stimulatedChannels, ...
                    cfg.timeBefore, cfg.timeAfter);

                save([saveDirectory currentSubject '_' currentFile '_' namesOut{file} '.mat'], '-struct', 'data')
                clear data

                save([saveHilbert 'hilbertSEEG_' currentSubject '_' currentFile '_' namesOut{file} '.mat'], '-struct', 'hilbertSeeg')
                save([saveHilbert 'hilbertEEG_'  currentSubject '_' currentFile '_' namesOut{file} '.mat'], '-struct', 'hilbertEeg')
                clear hilbert

            end
        end

        preprocessTag = 'preprocessingComplete';
        writematrix(preprocessTag, [subjectDirectory 'preprocessComplete.txt'])

    end
end
